### ISSUE TITLE
Microphysics scheme questions

### ISSUE THREAD

**Issue by jiskattema** [jiskattema/dales#1]
modbulkmicro_point.f90
- [x] l_sb_inuc_expl not implemented (line 465)
- [x] output of tendencies *dq_ci_dep*, *dq_hs_dep*. *dq_hg_dep* is after the cor_deposit3 correction, line 870
- [x] if *not l_sb_lim_aggr*, *E_ab* was unset? setting it to zero now. line 942
- [x] elseif statement should be an else. line 1367
- [x] if not *(D_cl.gt.D_c_a).and.(D_hg.gt.D_i0)*, can we turn off coll_gcg3? line 1474
- [x] if not *(D_cl.gt.D_c_a).and.(D_ci.gt.D_i0)*, can we turn off coll_ici3? line 1219
- [x] if not *(D_cl.gt.D_c_a).and.(D_hs.gt.D_i0)*, can we turn off coll_scs3? line 1323
- [x] evapmelting3: threshold for melting snow, should that be q_hs.gt.qicemin? line 2229
- [x] evapmelting3: threshold for melting graupel, should that be q_hg.gt.qicemin? line 2247
- [x] accretion3: when not *l_sb_classic*, should accretion happen when *q_hr < q_hr_min*? line 2501
- [x] evap_rain3: is the use of unlimited x_hrf correct? line 2617
- [x] satadj3: limit on *dn_cl_sa* is this now correct? is used to include svp(in_cl) (to include tendencies from outside the scheme?). I now initialize n_clp from svp(in_cl). line 2718 and 2751
- [x] sb_evmelt3: line 2997 and 3000, should the limit also include the tendency? *-n_cl/delt - n_clp* 
- [x] integrals_bulk3: do we need to limit x_hr? line 370 and 389

modbulkmicro_column.f90
- [x] nucleation3: original code went out of bound (memory corruption) for d ssat / dk . line 130. Is this better?
- [ ] line 360. Sedimentation threshold for rain
- [ ] line 528. Sedimentation threshold for snow
- [ ] line 726. Sedimentation threshold for ice
- [ ] line 831. Sedimentation threshold for cloud water
- [x] line 631, line 634. wrong variable (typo) be_hs => be_hg
- [x] lines 368 and 385, 412, Dvr_spl and x_hr are not calculated for different settings. Do we need to limit them, too?
- [ ] General sedimentation issue. The time-splitting scheme is to prevent stuff falling faster than 1 k-level. Why is then only the sedimentation at the first time split counted as precep (for instance *jn == 1* at line 464, but happens for all sedimentation, including the original bulkmicro and simpleice2 schemes, i think) 

General limiting question. Is there a preference for using the mass (q_ci), or mass + tendency (q_ci + q_cip)? 
Using the *m* variables (n_clm etc) like line 462, vs the *0* variables, line 3000

**Comment by jchylik** [comment]
> modbulkmicro_point.f90
> 
>     * [ ]  l_sb_inuc_expl not implemented (line 465)

- [x]  **T**, the warning is missing. Will be added after namelist reading

> 
>     * [ ]  output of tendencies _dq_ci_dep_, _dq_hs_dep_. _dq_hg_dep_ is after the cor_deposit3 correction, line 870

- [ ] **F**, output of the deposition tendencies should be after correction.

**Comment by jchylik** [comment]
> modbulkmicro_point.f90
> 
> * [ ]  if not l_sb_lim_aggr, E_ab was unset? setting it to zero now. line 942

- [x] **T**, in the array version, E_ab was initialize with 0. 

>     * [ ]  elseif statement should be an else. line 1367

- [x]  **T**

>     * [ ]  if not _(D_cl.gt.D_c_a).and.(D_hg.gt.D_i0)_, can we turn off coll_gcg3? line 1474

- [x]   **T**, in that case collection at given gridpoint does not happen.

>     * [ ]  if not _(D_cl.gt.D_c_a).and.(D_ci.gt.D_i0)_, can we turn off coll_ici3? line 1219

- [x]   **T**, in that case collection at given gridpoint does not happen.

>     * [ ]  if not _(D_cl.gt.D_c_a).and.(D_hs.gt.D_i0)_, can we turn off coll_scs3? line 1323

- [x]   **T**, in that case collection at given gridpoint does not happen.

>     * [ ]  evapmelting3: threshold for melting snow, should that be q_hs.gt.qicemin? line 2229

- [x] T, it should be qsnowmin

>     * [ ]  evapmelting3: threshold for melting graupel, should that be q_hg.gt.qicemin? line 2247

- [x] T, it should be qgrmin

>     * [ ]  accretion3: when not _l_sb_classic_, should accretion happen when _q_hr < q_hr_min_? line 2501

- [x] **T** Accretion in the old scheme happens when ((q_hr > q_hr_min) .and.(( q_cl> qcmin))

>     * [ ]  evap_rain3: is the use of unlimited x_hrf correct? line 2617

- [ ]  **F** That is intentional. It was already limited by  x_hrf = q_hr /(n_hr+eps0).
When replaced by x_hr, it can lead in case of many big raindrops to removal of too many of them.
(x_hr<x_hrf =>   phi/x_hr>phi/x_hrf )

>     * [ ]  satadj3: limit on _dn_cl_sa_ is this now correct? is used to include svp(in_cl) (to include tendencies from outside the scheme?). I now initialize n_clp from svp(in_cl). line 2718 and 2751

- [x] **T**: That makes sense. If n_clp is initialized with svp(in_cl), the svp here is not needed anymore.

>     * [ ]  sb_evmelt3: line 2997 and 3000, should the limit also include the tendency? _-n_cl/delt - n_clp_

- [x] **T**: the best would be to correct 
`(-n_em/delt)-n_ep`
where n_ep is n_hsp, n_hgp, n_cip
and n_em is svm(in_hs) etc.

>     * [ ]  integrals_bulk3: do we need to limit x_hr? line 370 and 389

- [x]  **F**, we should keep limiting it because of calculations of heterogeneous freezing

> modbulkmicro_column.f90
> 
>     * [ ]  nucleation3: original code went out of bound (memory corruption) for d ssat / dk . line 130. Is this better?

- [x]  **F**, it looks good now, but it would make sense to calculate just
do k=2,k1-1
We do not want cloud nucleation at the first model layer (and at the top one none is expected).

>     * [ ]  line 360. Sedimentation threshold for rain
> 
>     * [ ]  line 528. Sedimentation threshold for snow
> 
>     * [ ]  line 726. Sedimentation threshold for ice
>
>     * [ ]  line 831. Sedimentation threshold for cloud water

- [ ] **T**, The correct limit should be smaller than qrmin (or q_hs_min etc.), but not yet tested what works best.

>     * [ ]  line 631, line 634. wrong variable (typo) be_hs => be_hg

- [x] **T**: that was a typo

>     * [ ]  lines 368 and 385, 412, Dvr_spl and x_hr are not calculated for different settings. Do we need to limit them, too?

- [x] **T**, That is a very good point, Dvr_spl should be calculated from xr_spl

**Comment by jchylik** [comment]
>     * [ ]  General sedimentation issue. The time-splitting scheme is to prevent stuff falling faster than 1 k-level. Why is then only the sedimentation at the first time split counted as precep (for instance _jn == 1_ at line 464, but happens for all sedimentation, including the original bulkmicro and simpleice2 schemes, i think)

A very good question. I kept it consistent with the warm microphysics, and never actually used this statistic. I can look at it later.
 
> General limiting question. Is there a preference for using the mass (q_ci), or mass + tendency (q_ci + q_cip)?
> Using the _m_ variables (n_clm etc) like line 462, vs the _0_ variables, line 3000

It is generally preferable to limit the tendencies by variables m +  update
i.e. ( -(n_clm/delt+n_clp) )

**Comment by jiskattema** [comment]
Thanks for the comments. I've updated my code accordingly.
I'll close this issue, and will use separate issues for the remaining questions (and new ones..)
