### ISSUE TITLE
saturation adjustment bulkmicro3

### ISSUE THREAD

**Issue by jiskattema** [jiskattema/dales#3]
In satadj3, there are comments like:

NOTE: threshold might be lower then threshold for cloud computations, obviously

but the conditions tested against are different for various settings and seem to contradict the comments:
* n_clm+n_clp*delt larger than 0;
* in clouds (q_cl_mask), and n_clm+n_clp*delt larger than 0;

**Comment by jchylik** [comment]
The better option of these two is
_n_clm+n_clp*delt larger than 0;_

as long as the timesteps are in order of seconds.

The reason is that we want to perform saturation adjustment even for newly nucleated clouds. 
However for shorter timesteps (~0.1 s), we should consider a different approach (future plans)

**Comment by jiskattema** [comment]
ok. going for n_clm + n_clp*delt .gt. 0.0, and added your comments
